# See: https://docs.github.com/en/actions/writing-workflows
---
name: Release

# Trigger on any tag creation:
on:
  push:
#    tags:
#      - "*"

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
            artifact: linux-arm-gnu
            target: aarch64-unknown-linux-gnu
            use-zigbuild: true
            glibc-version: 2.28
    name: Build ${{ matrix.artifact }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Enable multiarch on the Azure mirror
        if: runner.os == 'Linux'
        run: |
          sudo dpkg --add-architecture arm64
          # switch mirror to the main Ubuntu archive (which has arm64 indexes)
          sudo sed -i \
            -e 's|http://azure.archive.ubuntu.com/ubuntu|http://archive.ubuntu.com/ubuntu|g' \
            -e 's|http://security.ubuntu.com/ubuntu|http://archive.ubuntu.com/ubuntu|g' \
            /etc/apt/sources.list

      - name: Prepare cross‑compile dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config \
            libudev-dev libusb-1.0-0-dev \
            gcc-aarch64-linux-gnu \
            pkg-config-aarch64-linux-gnu \
            libudev-dev:arm64 \
            libusb-1.0-0-dev:arm64

      - name: Build
        uses: asimov-platform/build-rust-action@v2
        env:
          PKG_CONFIG_ALLOW_CROSS: "1"
          PKG_CONFIG: aarch64-linux-gnu-pkg-config
        with:
          target: ${{ matrix.target }}
          artifact-name: ${{ matrix.artifact }}
          artifact-prefix: asimov
          binary-name: asimov-account
          binary-extension: ${{ matrix.extension }}
          strip-artifact: ${{ matrix.strip || 'false' }}
          use-zigbuild: ${{ matrix.use-zigbuild || 'false' }}
          rust-toolchain: 1.81.0

  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    permissions:
      contents: write
    steps:
      - name: Release
        uses: asimov-platform/release-action@v2
        with:
          token: ${{ secrets.PAT_RELEASE }}
          changelog-path: CHANGES.md
